### ISSUE TITLE
babel-node incompatibility in v7

### ISSUE THREAD

**Issue by tiagojufr** [elastic/require-in-the-middle#72]
I have `require-in-the-middle` in my project as a transitive dependency from `opentelemetry`. After upgrading some opentelemetry dependencies, I got this error while running my app in development mode:

```
$ babel-node src --extensions ".js,.ts" --require ./src/boot.ts src/index.ts 
C:\<path_to_my_project>\node_modules\@babel\core\lib\parser\index.js:74
    throw err;
    ^

AssertionError [ERR_ASSERTION]: unexpected that there is no Module entry for "C:\<path_to_my_project>\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js" in require.cache
    at ExportsCache.set (C:\<path_to_my_project>\node_modules\require-in-the-middle\index.js:89:7)
    at Module.Hook._require.Module.require (C:\<path_to_my_project>\node_modules\require-in-the-middle\index.js:249:17)
    at Module.Hook._require.Module.require (C:\<path_to_my_project>\node_modules\require-in-the-middle\index.js:179:39)
    at require (node:internal/modules/cjs/helpers:103:18)
    at parse (C:\<path_to_my_project>\node_modules\@babel\core\src\parser\index.ts:2:1)
    at parser (C:\<path_to_my_project>\node_modules\@babel\core\src\parser\index.ts:28:14)
    at parser.next (<anonymous>)
    at normalizeFile (C:\<path_to_my_project>\node_modules\@babel\core\src\transformation\normalize-file.ts:51:24)
    at normalizeFile.next (<anonymous>)
    at run (C:\<path_to_my_project>\node_modules\@babel\core\src\transformation\index.ts:38:36)
    at run.next (<anonymous>)
    at transform (C:\<path_to_my_project>\node_modules\@babel\core\src\transform.ts:29:20)
    at transform.next (<anonymous>)
    at evaluateSync (C:\<path_to_my_project>\node_modules\gensync\index.js:251:28)
    at fn (C:\<path_to_my_project>\node_modules\gensync\index.js:89:14)
    at stopHiding - secret - don't use this - v1 (C:\<path_to_my_project>\node_modules\@babel\core\src\errors\rewrite-stack-trace.ts:97:14)
    at Object.transformSync (C:\<path_to_my_project>\node_modules\@babel\core\src\transform.ts:66:52)
    at transformSync (C:\<path_to_my_project>\node_modules\@babel\register\src\worker\transform.js:94:33)
    at Function.handleMessage (C:\<path_to_my_project>\node_modules\@babel\register\src\worker\handle-message.js:15:16)
    at LocalClient.<anonymous> (C:\<path_to_my_project>\node_modules\@babel\register\src\worker-client.js:103:27)
    at LocalClient.transform (C:\<path_to_my_project>\node_modules\@babel\register\src\worker-client.js:40:16)
    at compile (C:\<path_to_my_project>\node_modules\@babel\register\src\hook.js:57:25)
    at compileBabel7 (C:\<path_to_my_project>\node_modules\@babel\register\src\hook.js:48:14)
    at Module._compile (C:\<path_to_my_project>\node_modules\pirates\lib\index.js:130:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .ts] (C:\<path_to_my_project>\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at Module.Hook._require.Module.require (C:\<path_to_my_project>\node_modules\require-in-the-middle\index.js:179:39)
    at Module.Hook._require.Module.require (C:\<path_to_my_project>\node_modules\require-in-the-middle\index.js:179:39)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\<path_to_my_project>\packages\api\src\/index.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._compile (C:\<path_to_my_project>\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.newLoader [as .ts] (C:\<path_to_my_project>\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.runMain (node:internal/modules/run_main:81:12)
    at Object.<anonymous> (C:\<path_to_my_project>\node_modules\@babel\node\src\_babel-node.ts:222:12)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v18.13.0
```
This only happens with `require-in-the-middle@7.1.0`. If I downgrade to `6.0.0` I don't have this issue. I also noticed that if I run my app in production mode (`node --require ./build/boot.js build/index.js`), it works. This seems to be some incompatibility between `@babel/node` and `require-in-the-middle`. I'm using `@babel/node@7.22.1`.

**Comment by trentm** [comment]
From the changelog, this is almost certainly the change that is affecting you:

> - Use the Node.js `require.cache` for caching the exports returned from a
>   Hook's `onrequire`. This allows users to delete entries from `require.cache`
>   to trigger a re-load (and re-run of the hook's `onrequire`) of a module the
>   next time it is required -- as mentioned at
>   https://nodejs.org/docs/latest/api/all.html#all_modules_requirecache
>   (https://github.com/elastic/require-in-the-middle/issues/61)

This post points to a similar issue: https://stackoverflow.com/questions/42781043/clearing-node-js-cache-when-loading-non-js-files-e-g-graphql-language-defeniti
and mentions that one can set the `BABEL_DISABLE_CACHE=1` environment variable to disable Babel's cache.
It would be interesting to know if that works around the issue for you.  I'm not sure this is the same thing you are seeing.

However, we should still fix require-in-the-middle so it doesn't *crash* in this case.

I tried to play with Babel and require-in-the-middle a little bit to see if I could reproduce, but I haven't been able to. Are you able to create a small reproduction case?  Or if not, some more details might help: what versions of modules you are using (`npm ls -a`), what that `src/boot.js` is doing, what `src/index.ts` is doing, what your babel config is. Thanks.

**Comment by trentm** [comment]
I would definitely like to be able to repro so I can feel confident in the fix.

My guess is that the interaction problem is because of this Babel change: https://github.com/babel/babel/pull/12665
Basically, when babel is requiring/compiling some of its own internal modules, it swaps in/out its own `internalModuleCache` onto `Module._cache` (which is what `require.cache` is set to in node internals).

**Comment by tiagojufr** [comment]
`BABEL_DISABLE_CACHE=1` actually works for me! Thanks! I'll try to create a small project that reproduces the issue for you, but it may take me some time, as this is a company project and I can't share it. Here are the relevant pieces I can give you:

package.json:
```
"dependencies": {
    "@opentelemetry/api": "~1.4.1",
    "@opentelemetry/instrumentation-express": "^0.32.3",
    "@opentelemetry/instrumentation-graphql": "^0.34.2",
    "@opentelemetry/instrumentation-http": "^0.37.0",
    "@opentelemetry/propagator-b3": "^1.13.0",
    "@opentelemetry/sdk-node": "^0.39.1",
    "express": "^4.18.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.21.5",
    "@babel/core": "^7.22.1",
    "@babel/node": "^7.22.1",
    "@babel/preset-env": "^7.22.2",
    "@babel/preset-typescript": "^7.21.5",
    "nodemon": "^2.0.22",
    "typescript": "^5.0.4"
  },
  "babel": {
    "presets": [
      "@babel/env",
      "@babel/typescript"
    ],
    "targets": "node 18"
  },
  "scripts": {
    "build": "yarn build:source && yarn build:types",
    "build:source": "babel src --out-dir build --extensions \".js,.ts\" --source-maps inline --ignore \"**/__mocks__\" --ignore \"**/*.test.tsx?\"",
    "build:types": "tsc --resolveJsonModule --declaration --emitDeclarationOnly --esModuleInterop true --outDir build src/index.ts",
    "dev": "nodemon --require ./src/boot.ts src/index.ts --exec babel-node src --extensions \".js,.ts\"",
    "start": "node --require ./build/boot.js build/index.js"
  }
```

src/boot.ts:
```
import * as opentelemetry from '@opentelemetry/sdk-node'
import {HttpInstrumentation} from '@opentelemetry/instrumentation-http'
import {ExpressInstrumentation} from '@opentelemetry/instrumentation-express'
import {GraphQLInstrumentation} from '@opentelemetry/instrumentation-graphql'

// Configure OpenTelemetry
const sdk = new opentelemetry.NodeSDK({
  traceExporter: new opentelemetry.tracing.InMemorySpanExporter(),
  instrumentations: [
    new HttpInstrumentation(),
    new ExpressInstrumentation(),
    new GraphQLInstrumentation()
  ]
})
sdk.start()
```

src/index.ts:
We do a lot of stuff here but basically we start an express server with an apollo-server for our GQL API and a few other express endpoints. I don't think this file matters to much as long as you start an express server so opentelemetry can perform its magic and call `require-in-the-middle`. 

We use yarn in our scripts but you can easily change them to npm if needed. Please let me know if you need anything else, I'm probably over simplifying this :)

**Comment by tiagojufr** [comment]
@trentm I was able to reproduce the issue in this small project: https://github.com/tiagojufr/opentelemetry-babel-require-in-the-middle-repro. See instructions in the README file. Please try it out and let me know!

**Comment by trentm** [comment]
Thanks very much for the repro repo!

- I needed to delete your package-lock.json file to install b/c I think you use a custom npm registry. :)
- I added some debugging prints to the `@babel/register` module:

```
node_modules/@babel/register/lib/nodeWrapper.js
4:console.log('XXX register: set Module._cache = internalModuleCache')
7:console.log('XXX register: set Module._cache = globalModuleCache')

node_modules/@babel/register/lib/hook.js
37:      console.log('XXX register/compileBabel7(): set Module._cache = internalModuleCache for "%s"', filename)
42:      console.log('XXX register/compileBabel7(): restore Module._cache = globalModuleCache after compile "%s"', filename)
```

- And to your boot.ts:

```diff
diff --git a/src/boot.ts b/src/boot.ts
index 81f6bfc..7d97753 100644
--- a/src/boot.ts
+++ b/src/boot.ts
@@ -1,3 +1,4 @@
+console.log('XXX start evaluating boot.ts')
 import * as opentelemetry from "@opentelemetry/sdk-node";
 import { HttpInstrumentation } from "@opentelemetry/instrumentation-http";
 import { ExpressInstrumentation } from "@opentelemetry/instrumentation-express";
@@ -5,11 +6,12 @@ import { GraphQLInstrumentation } from "@opentelemetry/instrumentation-graphql";

 // Configure OpenTelemetry
 const sdk = new opentelemetry.NodeSDK({
-  traceExporter: new opentelemetry.tracing.InMemorySpanExporter(),
+  traceExporter: new opentelemetry.tracing.ConsoleSpanExporter(),
   instrumentations: [
     new HttpInstrumentation(),
     new ExpressInstrumentation(),
     new GraphQLInstrumentation(),
   ],
 });
+console.log('XXX sdk.start()')
 sdk.start();
```

- Then I ran with debug logging of require-in-the-middle turned on. Note that the very first run does not fail -- when `@babel/register` is first creating its cache file. Subsequent runs fail:

```
% DEBUG=require-in-the-middle npm run dev

> opentelemetry-babel-require-in-the-middle-repro@0.0.1 dev
> nodemon --require ./src/boot.ts src/index.ts --exec babel-node src --extensions ".js,.ts"

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `babel-node --require ./src/boot.ts src/index.ts src --extensions .js,.ts`
XXX register: set Module._cache = internalModuleCache
XXX register: set Module._cache = globalModuleCache
XXX register/compileBabel7(): set Module._cache = internalModuleCache for "/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/src/boot.ts"
XXX register/compileBabel7(): restore Module._cache = globalModuleCache after compile "/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/src/boot.ts"

... many lines of `XXX register/compileBabel7() ...` while `@babel/register` loads its cache and handles `import`s in "boot.ts".
```

Finally it starts evaluating "boot.ts" which starts the "require-in-the-middle" hook:

```
...
XXX start evaluating boot.ts
  require-in-the-middle registering require hook +0ms
XXX sdk.start()
XXX register/compileBabel7(): set Module._cache = internalModuleCache for "/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/src/index.ts"
  require-in-the-middle processing core module require('path'): path +10ms
  require-in-the-middle calling require hook: path +0ms
  require-in-the-middle returning module: path +0ms
  require-in-the-middle processing non-core module require('@babel/parser'): /Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/parser/lib/index.js +1ms
  require-in-the-middle resolved filename to module: @babel/parser (id: @babel/parser, resolved: @babel/parser/lib, basedir: /Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/parser) +0ms
XXX register/compileBabel7(): restore Module._cache = globalModuleCache after compile "/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/src/index.ts"
/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/core/lib/parser/index.js:74
    throw err;
    ^

AssertionError [ERR_ASSERTION]: unexpected that there is no Module entry for "/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/parser/lib/index.js" in require.cache
    at ExportsCache.set (/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/require-in-the-middle/index.js:90:7)
    at Module.Hook._require.Module.require (/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/require-in-the-middle/index.js:256:17)
    at require (node:internal/modules/cjs/helpers:110:18)
    at parse (/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/core/src/parser/index.ts:2:1)
    at parser (/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/core/src/parser/index.ts:28:14)
    at parser.next (<anonymous>)
    at normalizeFile (/Users/trentm/tmp/opentelemetry-babel-require-in-the-middle-repro/node_modules/@babel/core/src/transformation/normalize-file.ts:51:24)
...
```

What happened here is that when `require-in-the-middle`s handler for `require()` attempted to cache the processed `'@babel/parser'` module on `require.cache` **it failed** because require.cache didn't have that module **because `@babel/register` had loaded the file from *its* cache**.

# Solution

My solution is going to be to have `require-in-the-middle` *attempt* to use `require.cache` for non-core modules, but if it doesn't find `require.cache[filename]` that it expects, it will fallback to caching those exports locally -- the same as it used to do before require-in-the-middle@7.0.0.


# Showing it working with preliminary fix

After my preliminary fix, here is part of the output from running your repro
showing it gathering OpenTelemetry spans using the `ConsoleSpanExporter`:


```
...
Server listening on port 3000


{
  traceId: '044ffb136aad76ec0e8c3ac03f012cb6',
  parentId: '956e75ee18a299dd',
  traceState: undefined,
  name: 'middleware - query',
  id: '308456029111e33d',
  kind: 0,
  timestamp: 1685481402026000,
  duration: 456,
  attributes: {
    'http.route': '/',
    'express.name': 'query',
    'express.type': 'middleware'
  },
  status: { code: 0 },
  events: [],
  links: []
}
{
  traceId: '044ffb136aad76ec0e8c3ac03f012cb6',
  parentId: '956e75ee18a299dd',
  traceState: undefined,
  name: 'middleware - expressInit',
  id: '36342b2f2a9c2d1b',
  kind: 0,
  timestamp: 1685481402027000,
  duration: 501,
  attributes: {
    'http.route': '/',
    'express.name': 'expressInit',
    'express.type': 'middleware'
  },
  status: { code: 0 },
  events: [],
  links: []
}
{
  traceId: '044ffb136aad76ec0e8c3ac03f012cb6',
  parentId: '956e75ee18a299dd',
  traceState: undefined,
  name: 'request handler - /',
  id: '9e64ef053d600513',
  kind: 0,
  timestamp: 1685481402027000,
  duration: 69,
  attributes: {
    'http.route': '/',
    'express.name': '/',
    'express.type': 'request_handler'
  },
  status: { code: 0 },
  events: [],
  links: []
}
{
  traceId: '044ffb136aad76ec0e8c3ac03f012cb6',
  parentId: undefined,
  traceState: undefined,
  name: 'GET /',
  id: '956e75ee18a299dd',
  kind: 1,
  timestamp: 1685481402022000,
  duration: 11641,
  attributes: {
    'http.url': 'http://localhost:3000/',
    'http.host': 'localhost:3000',
    'net.host.name': 'localhost',
    'http.method': 'GET',
    'http.scheme': 'http',
    'http.target': '/',
    'http.user_agent': 'curl/7.88.1',
    'http.flavor': '1.1',
    'net.transport': 'ip_tcp',
    'net.host.ip': '::ffff:127.0.0.1',
    'net.host.port': 3000,
    'net.peer.ip': '::ffff:127.0.0.1',
    'net.peer.port': 49966,
    'http.status_code': 200,
    'http.status_text': 'OK',
    'http.route': ''
  },
  status: { code: 0 },
  events: [],
  links: []
}
```

**Comment by trentm** [comment]
Note that it will take a while for a new release and for OTel to pick that up.

**Comment by tiagojufr** [comment]
ok thank you very much, I'll try with the new version
